#!/usr/bin/env python3
"""Generate and validate public-safe PSP-P04 offer artifacts."""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "institutio/positioning/commercial-contract.yaml"
OUTPUT_DIR = ROOT / "docs/positioning/offers"

OFFER_FILES = {
    "audit": "agentic-delivery-audit.md",
    "install": "governance-install.md",
    "retainer": "bounded-delivery-governance-retainer.md",
    "partnership_review": "product-operating-partnership-review.md",
}
QUALIFICATION_FILE = "qualification-and-routing.md"
EXPECTED_FILES = frozenset((*OFFER_FILES.values(), QUALIFICATION_FILE))
WORK_ITEMS = {
    "audit": "PSP-P04-W01",
    "install": "PSP-P04-W02",
    "retainer": "PSP-P04-W03",
    "partnership_review": "PSP-P04-W07",
}
PRIMARY_SEQUENCE = ["audit", "install", "retainer"]
COMMERCIAL_ROUTES = frozenset((*PRIMARY_SEQUENCE, "partnership_review"))
EXPECTED_ROUTE_PRIORITY = [
    "human_review",
    "decline",
    "recruiter",
    "partnership_review",
    "retainer",
    "install",
    "audit",
]
EXPECTED_OFFER_CONTRACT = {
    "audit": {
        "stage": "diagnose",
        "position": "primary_entry",
        "authority_mode": "read_only",
        "anchor_id": "PRICE-AUDIT",
        "range_id": "RANGE-AUDIT",
        "approval_gate": "HG-PRICE-ANCHORS",
    },
    "install": {
        "stage": "implement",
        "position": "primary_expansion",
        "authority_mode": "bounded_write",
        "anchor_id": "PRICE-INSTALL",
        "range_id": "RANGE-INSTALL",
        "approval_gate": "HG-PRICE-ANCHORS",
    },
    "retainer": {
        "stage": "sustain",
        "position": "primary_continuity",
        "authority_mode": "advisory_with_named_changes",
        "anchor_id": "PRICE-RETAINER",
        "range_id": "RANGE-RETAINER",
        "approval_gate": "HG-PRICE-ANCHORS",
    },
    "partnership_review": {
        "stage": "diligence",
        "position": "secondary_only",
        "authority_mode": "diligence_only",
        "anchor_id": "PRICE-PARTNERSHIP",
        "range_id": "RANGE-PARTNERSHIP",
        "approval_gate": "HG-OPERATOR-TERMS",
    },
}
REQUIRED_OFFER_FIELDS = frozenset(
    {
        "id",
        "name",
        "stage",
        "position",
        "buyer",
        "trigger",
        "entry_criteria",
        "promise",
        "deliverables",
        "exclusions",
        "timeline",
        "authority",
        "evidence",
        "economics",
        "handoff",
        "escalation",
        "claim_refs",
    }
)
REQUIRED_AUTHORITY_FIELDS = frozenset({"mode", "boundary"})
REQUIRED_EVIDENCE_FIELDS = frozenset({"acceptance", "artifacts"})
REQUIRED_ECONOMICS_FIELDS = frozenset(
    {
        "model",
        "anchor_id",
        "range_id",
        "approval_gate",
        "public_price",
        "capacity_rule",
        "discount_rule",
    }
)
REQUIRED_PROHIBITED_EFFECTS = frozenset(
    {
        "public-surface publication",
        "issue or phase closure",
        "leaf or phase receipt submission",
        "merge to main",
        "outbound sending",
        "spend or account mutation",
        "DNS or visibility changes",
        "contractual or partnership commitment",
    }
)

PRIVATE_PATTERNS = (
    re.compile(r"(?:^|[\s`(])(?:/Users/|/home/|/private/|~/|file://)", re.IGNORECASE),
    re.compile(r"\b[A-Z]:\\Users\\", re.IGNORECASE),
    re.compile(
        r"(?:\.limen-private/|\.agent-runtime/|session-state/|archived_sessions/|"
        r"private-vault|positioning-seeds\.json)",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b",
        re.IGNORECASE,
    ),
)
PRICE_PATTERNS = (
    re.compile(r"[$£€]\s*\d"),
    re.compile(
        r"\b\d+(?:[,.]\d+)*\s*(?:USD|EUR|GBP|dollars?|euros?|pounds?)\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b\d+(?:[,.]\d+)*\s*(?:/\s*(?:hr|hour|day|month|year)|per\s+(?:hour|day|month|year))\b",
        re.IGNORECASE,
    ),
    re.compile(r"\b\d+(?:\.\d+)?\s*[kK]\b"),
    re.compile(
        r"\b(?:fee|price|rate|discount|margin|equity|revenue[- ]share|transfer\s+term)"
        r"\s*(?:is|of|at|:|=)?\s*[$£€]?\s*\d",
        re.IGNORECASE,
    ),
    re.compile(
        r"\b\d+(?:\.\d+)?\s*%\s*(?:discount|margin|equity|revenue[- ]share)\b",
        re.IGNORECASE,
    ),
)
NUMERIC_TOKEN_PATTERN = re.compile(r"\b\d+(?:[,.]\d+)*(?:\s*%)?\b")
FRONT_DOOR_MARKER = "**Front-door next step:**"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/positioning-offer-artifacts.py from the canonical "
    "commercial contract; do not edit by hand. -->"
)


class OfferArtifactValidationError(ValueError):
    """Raised when the canonical source cannot be loaded safely."""


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


def _sequence(value: Any) -> Sequence[Any]:
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        return value
    return ()


def _strings(value: Any) -> Iterable[str]:
    if isinstance(value, str):
        yield value
    elif isinstance(value, Mapping):
        for item in value.values():
            yield from _strings(item)
    elif isinstance(value, Sequence) and not isinstance(value, (str, bytes)):
        for item in value:
            yield from _strings(item)


def _require(errors: list[str], condition: bool, message: str) -> None:
    if not condition:
        errors.append(message)


def _require_fields(
    errors: list[str],
    value: Any,
    fields: Iterable[str],
    label: str,
) -> Mapping[str, Any]:
    mapping = _mapping(value)
    if not mapping:
        errors.append(f"{label} must be a non-empty mapping")
    for field in sorted(fields):
        field_value = mapping.get(field)
        if field not in mapping or field_value is None or (isinstance(field_value, str) and not field_value.strip()):
            errors.append(f"{label} missing required field: {field}")
    return mapping


def _offer_map(data: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    ladder = _mapping(data.get("offer_ladder"))
    result: dict[str, Mapping[str, Any]] = {}
    for raw_offer in _sequence(ladder.get("items")):
        offer = _mapping(raw_offer)
        offer_id = offer.get("id")
        if isinstance(offer_id, str):
            result[offer_id] = offer
    secondary = _mapping(ladder.get("secondary"))
    secondary_id = secondary.get("id")
    if isinstance(secondary_id, str):
        result[secondary_id] = secondary
    return result


def _audience_map(data: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    result: dict[str, Mapping[str, Any]] = {}
    for raw_audience in _sequence(data.get("audiences")):
        audience = _mapping(raw_audience)
        audience_id = audience.get("id")
        if isinstance(audience_id, str):
            result[audience_id] = audience
    return result


def _rule_matches(rule: Mapping[str, Any], facts: Mapping[str, Any]) -> bool:
    all_terms = _sequence(rule.get("all"))
    any_terms = _sequence(rule.get("any"))
    none_terms = _sequence(rule.get("none"))
    return (
        all(facts.get(str(term), False) is True for term in all_terms)
        and (not any_terms or any(facts.get(str(term), False) is True for term in any_terms))
        and not any(facts.get(str(term), False) is True for term in none_terms)
    )


def _priority_value(rule: Mapping[str, Any]) -> int:
    priority = rule.get("priority")
    return priority if isinstance(priority, int) else 10**9


def validate_artifact_text(label: str, text: str) -> list[str]:
    """Return public-safety violations found in one rendered artifact."""
    errors: list[str] = []
    for pattern in PRIVATE_PATTERNS:
        match = pattern.search(text)
        if match:
            errors.append(f"private path or source leaked into {label}: {match.group(0).strip()}")
    for pattern in PRICE_PATTERNS:
        match = pattern.search(text)
        if match:
            errors.append(f"numeric price leaked into {label}: {match.group(0).strip()}")
    return errors


def validate_contract(data: Mapping[str, Any]) -> list[str]:
    """Validate the source fields and safety invariants used by public artifacts."""
    errors: list[str] = []
    _require(
        errors,
        data.get("schema_version") == "limen.positioning_commercial_contract.v1",
        "schema version must be limen.positioning_commercial_contract.v1",
    )

    contract = _require_fields(
        errors,
        data.get("contract"),
        {
            "status",
            "work_chunk",
            "canonical_source",
            "formal_dependency",
            "prohibited_preflight_effects",
        },
        "contract",
    )
    _require(
        errors,
        isinstance(contract.get("status"), str),
        "contract status must be explicit text",
    )
    _require(
        errors,
        contract.get("work_chunk") == "PSP-C03",
        "offer contract must remain owned by PSP-C03",
    )
    _require(
        errors,
        contract.get("canonical_source") == "institutio/positioning/commercial-contract.yaml",
        "canonical source path drifted",
    )
    dependency = _require_fields(
        errors,
        contract.get("formal_dependency"),
        {"chunk_id", "phase_id", "state", "consequence"},
        "contract.formal_dependency",
    )
    _require(
        errors,
        isinstance(dependency.get("state"), str),
        "formal dependency state must be explicit text",
    )
    prohibited_effects = [str(effect) for effect in _sequence(contract.get("prohibited_preflight_effects"))]
    for effect in sorted(REQUIRED_PROHIBITED_EFFECTS):
        _require(
            errors,
            any(effect in recorded_effect for recorded_effect in prohibited_effects),
            f"missing prohibited preflight effect: {effect}",
        )

    ladder = _require_fields(
        errors,
        data.get("offer_ladder"),
        {"primary_sequence", "items", "secondary"},
        "offer_ladder",
    )
    primary_items = [_mapping(item) for item in _sequence(ladder.get("items"))]
    primary_ids = [item.get("id") for item in primary_items]
    _require(
        errors,
        list(_sequence(ladder.get("primary_sequence"))) == PRIMARY_SEQUENCE,
        "primary sequence must remain audit -> install -> retainer",
    )
    _require(
        errors,
        primary_ids == PRIMARY_SEQUENCE,
        f"primary offer order drifted: expected {PRIMARY_SEQUENCE}, found {primary_ids}",
    )

    secondary = _mapping(ladder.get("secondary"))
    all_offers = [*primary_items, secondary]
    all_offer_ids = [offer.get("id") for offer in all_offers]
    _require(
        errors,
        all_offer_ids == [*PRIMARY_SEQUENCE, "partnership_review"],
        "offer set must contain audit, install, retainer, and partnership_review exactly once",
    )

    signatures: dict[str, set[str]] = {
        "stage": set(),
        "position": set(),
        "trigger": set(),
        "promise": set(),
    }
    symbolic_ids: set[str] = set()
    for offer in all_offers:
        offer_id = str(offer.get("id", "unknown"))
        required_fields = set(REQUIRED_OFFER_FIELDS)
        if offer_id == "partnership_review":
            required_fields.update({"public_cta", "disclosure_entry"})
        checked_offer = _require_fields(
            errors,
            offer,
            required_fields,
            f"offer {offer_id}",
        )
        for list_field in (
            "entry_criteria",
            "deliverables",
            "exclusions",
            "escalation",
            "claim_refs",
        ):
            _require(
                errors,
                bool(_sequence(checked_offer.get(list_field))),
                f"offer {offer_id} field {list_field} must be a non-empty list",
            )

        authority = _require_fields(
            errors,
            checked_offer.get("authority"),
            REQUIRED_AUTHORITY_FIELDS,
            f"offer {offer_id}.authority",
        )
        evidence = _require_fields(
            errors,
            checked_offer.get("evidence"),
            REQUIRED_EVIDENCE_FIELDS,
            f"offer {offer_id}.evidence",
        )
        _require(
            errors,
            bool(_sequence(evidence.get("artifacts"))),
            f"offer {offer_id}.evidence.artifacts must be a non-empty list",
        )
        economics = _require_fields(
            errors,
            checked_offer.get("economics"),
            REQUIRED_ECONOMICS_FIELDS,
            f"offer {offer_id}.economics",
        )

        expected = EXPECTED_OFFER_CONTRACT.get(offer_id)
        if expected:
            for field in ("stage", "position"):
                _require(
                    errors,
                    checked_offer.get(field) == expected[field],
                    f"offer {offer_id} {field} must remain {expected[field]}",
                )
            _require(
                errors,
                authority.get("mode") == expected["authority_mode"],
                f"offer {offer_id} authority must remain {expected['authority_mode']}",
            )
            for field in ("anchor_id", "range_id", "approval_gate"):
                _require(
                    errors,
                    economics.get(field) == expected[field],
                    f"offer {offer_id} {field} must remain {expected[field]}",
                )
        _require(
            errors,
            economics.get("public_price") == "prohibited",
            f"offer {offer_id} must prohibit public pricing",
        )

        for signature_name in signatures:
            signature = str(checked_offer.get(signature_name, "")).strip().lower()
            if signature and signature in signatures[signature_name]:
                errors.append(f"offer overlap: duplicate {signature_name} boundary for {offer_id}")
            signatures[signature_name].add(signature)
        for symbolic_field in ("anchor_id", "range_id"):
            symbolic = str(economics.get(symbolic_field, ""))
            if symbolic in symbolic_ids:
                errors.append(f"offer overlap: duplicate symbolic economics ID {symbolic}")
            symbolic_ids.add(symbolic)

    offer_by_id = _offer_map(data)
    audit_blob = " ".join(_strings(offer_by_id.get("audit", {}))).lower()
    install_blob = " ".join(_strings(offer_by_id.get("install", {}))).lower()
    retainer_blob = " ".join(_strings(offer_by_id.get("retainer", {}))).lower()
    partnership_blob = " ".join(_strings(offer_by_id.get("partnership_review", {}))).lower()
    _require(
        errors,
        "production mutation or deployment" in audit_blob,
        "Audit must exclude production mutation or deployment",
    )
    _require(
        errors,
        "one named sponsor, internal owner, team, and pipeline" in install_blob,
        "Install must remain bounded to one named team or pipeline",
    )
    _require(
        errors,
        "an accepted installed baseline" in retainer_blob
        and "on-call, emergency, or round-the-clock response" in retainer_blob
        and "unlimited implementation" in retainer_blob,
        ("Retainer must require an installed baseline and exclude on-call or unlimited implementation"),
    )
    _require(
        errors,
        secondary.get("public_cta") is False
        and secondary.get("disclosure_entry") == "L3"
        and secondary.get("position") == "secondary_only",
        "public partnership promotion is prohibited; partnership must remain secondary and L3-only",
    )
    for phrase in (
        "no equity, licence, revenue, custody, or transfer term is implied",
        "no operating, account, custody, financial, publication, or legal authority exists",
        "no economic term exists before readiness",
    ):
        _require(
            errors,
            phrase in partnership_blob,
            f"partnership no-implied-terms boundary missing: {phrase}",
        )

    audiences = _audience_map(data)
    _require(
        errors,
        set(audiences) == {"direct_client", "recruiter_executive", "product_operating_partner"},
        ("audience set must remain direct client, recruiter/executive, and product-operating partner"),
    )
    direct_client = audiences.get("direct_client", {})
    direct_cta = str(direct_client.get("primary_cta", ""))
    _require(
        errors,
        direct_client.get("public_door") is True and "Agentic Delivery Audit" in direct_cta,
        "the direct-client front door must remain the Agentic Delivery Audit",
    )
    _require(
        errors,
        "partner" not in direct_cta.lower(),
        "public partnership promotion leaked into the direct-client CTA",
    )
    partner_audience = audiences.get("product_operating_partner", {})
    partner_cta = str(partner_audience.get("primary_cta", "")).lower()
    _require(
        errors,
        partner_audience.get("public_door") is False
        and partner_audience.get("disclosure_entry") == "L3"
        and "no public call to action" in partner_cta
        and "qualified diligence" in partner_cta,
        "product-operating partner audience must remain closed-front-door L3 diligence",
    )

    narrative_by_id = {
        str(level.get("id")): level for level in (_mapping(item) for item in _sequence(data.get("narrative_ladder")))
    }
    for level_id in ("L1", "L2"):
        level = narrative_by_id.get(level_id, {})
        _require(
            errors,
            "product_operating_partner" not in _sequence(level.get("audience_ids"))
            and "product_operating_partner" not in _mapping(level.get("next_actions")),
            f"public partnership promotion is prohibited in {level_id}",
        )
    _require(
        errors,
        "product_operating_partner" in _sequence(narrative_by_id.get("L3", {}).get("audience_ids")),
        "partnership diligence must remain available at L3",
    )

    economics = _require_fields(
        errors,
        data.get("economics_contract"),
        {"public_rule", "private_anchor_rule", "range_structure"},
        "economics_contract",
    )
    range_structure = _require_fields(
        errors,
        economics.get("range_structure"),
        {"floor", "target", "exception", "public_representation"},
        "economics_contract.range_structure",
    )
    public_rule = str(economics.get("public_rule", "")).lower()
    for term in (
        "numeric fee",
        "rate",
        "discount",
        "margin",
        "equity",
        "revenue-share",
        "transfer term",
        "public surface",
    ):
        _require(
            errors,
            term in public_rule,
            f"no-public-price rule missing term: {term}",
        )
    private_anchor_rule = str(economics.get("private_anchor_rule", "")).lower()
    _require(
        errors,
        "symbolic anchor id" in private_anchor_rule
        and "actual amount remains in its sanctioned private owner" in private_anchor_rule,
        "symbolic-anchor private custody rule drifted",
    )
    public_representation = str(range_structure.get("public_representation", ""))
    for range_id in (
        "RANGE-AUDIT",
        "RANGE-INSTALL",
        "RANGE-RETAINER",
        "RANGE-PARTNERSHIP",
    ):
        _require(
            errors,
            range_id in public_representation,
            f"public range rule missing {range_id}",
        )
    _require(
        errors,
        "never expose the underlying numbers" in public_representation.lower(),
        "public range rule must prohibit underlying-number disclosure",
    )
    public_economics_text = "\n".join(
        _strings(
            [
                economics,
                *[_mapping(offer.get("economics")) for offer in all_offers],
            ]
        )
    )
    numeric_economics = NUMERIC_TOKEN_PATTERN.search(public_economics_text)
    _require(
        errors,
        numeric_economics is None,
        (
            "numeric price leaked into canonical public economics"
            + (f": {numeric_economics.group(0)}" if numeric_economics else "")
        ),
    )

    qualification = _require_fields(
        errors,
        data.get("qualification"),
        {"routing_priority", "rules", "scenarios", "decline_language", "review_language"},
        "qualification",
    )
    rules = [_mapping(rule) for rule in _sequence(qualification.get("rules"))]
    route_priority = list(_sequence(qualification.get("routing_priority")))
    _require(
        errors,
        route_priority == EXPECTED_ROUTE_PRIORITY,
        f"routing priority drifted: expected {EXPECTED_ROUTE_PRIORITY}",
    )
    rule_ids = [str(rule.get("id")) for rule in rules]
    priorities = [rule.get("priority") if isinstance(rule.get("priority"), int) else None for rule in rules]
    _require(errors, len(rule_ids) == len(set(rule_ids)), "qualification rule IDs must be unique")
    _require(
        errors,
        len(priorities) == len(set(priorities)),
        "qualification priorities must be unique",
    )
    for rule in rules:
        rule_id = str(rule.get("id", "unknown"))
        _require_fields(
            errors,
            rule,
            {"id", "route", "priority", "any", "all", "none"},
            f"qualification rule {rule_id}",
        )
        _require(
            errors,
            isinstance(rule.get("priority"), int),
            f"qualification rule {rule_id}.priority must be an integer",
        )
        for condition in ("any", "all", "none"):
            _require(
                errors,
                isinstance(rule.get(condition), list),
                f"qualification rule {rule_id}.{condition} must be a list",
            )
    sorted_routes = [rule.get("route") for rule in sorted(rules, key=_priority_value)]
    _require(
        errors,
        sorted_routes == route_priority,
        "routing priority must match rule priority order",
    )
    operator_rules = [rule for rule in rules if rule.get("route") == "partnership_review"]
    _require(
        errors,
        len(operator_rules) == 1 and "public_front_door" in _sequence(operator_rules[0].get("none")),
        "partnership routing must explicitly exclude the public front door",
    )

    for raw_scenario in _sequence(qualification.get("scenarios")):
        scenario = _require_fields(
            errors,
            raw_scenario,
            {"id", "facts", "expected_route"},
            "qualification scenario",
        )
        scenario_id = str(scenario.get("id", "unknown"))
        facts = _mapping(scenario.get("facts"))
        _require(
            errors,
            bool(facts) and all(isinstance(value, bool) for value in facts.values()),
            f"scenario {scenario_id} facts must be non-empty booleans",
        )
        matches = sorted(
            (rule for rule in rules if _rule_matches(rule, facts)),
            key=_priority_value,
        )
        _require(errors, bool(matches), f"scenario {scenario_id} has no route")
        if matches:
            _require(
                errors,
                matches[0].get("route") == scenario.get("expected_route"),
                f"scenario {scenario_id} expected {scenario.get('expected_route')} "
                f"but routed to {matches[0].get('route')}",
            )
        commercial_matches = {str(rule.get("route")) for rule in matches if rule.get("route") in COMMERCIAL_ROUTES}
        _require(
            errors,
            len(commercial_matches) <= 1,
            f"offer overlap in scenario {scenario_id}: {sorted(commercial_matches)}",
        )

    public_payload = {
        "contract": {
            "canonical_source": contract.get("canonical_source"),
            "formal_dependency": dependency,
            "prohibited_preflight_effects": contract.get("prohibited_preflight_effects"),
        },
        "offers": all_offers,
        "qualification": qualification,
        "economics": {
            "public_rule": economics.get("public_rule"),
            "private_anchor_rule": economics.get("private_anchor_rule"),
            "public_representation": range_structure.get("public_representation"),
        },
        "front_door_cta": direct_cta,
        "partnership_entry": partner_audience.get("primary_cta"),
    }
    errors.extend(validate_artifact_text("canonical PSP-P04 public payload", "\n".join(_strings(public_payload))))
    return errors


def _bullet_lines(values: Sequence[Any]) -> list[str]:
    return [f"- {value}" for value in values]


def _code_values(values: Sequence[Any]) -> str:
    if not values:
        return "—"
    return ", ".join(f"`{value}`" for value in values)


def _table_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _preamble(data: Mapping[str, Any], title: str, work_item: str) -> list[str]:
    contract = _mapping(data["contract"])
    dependency = _mapping(contract["formal_dependency"])
    return [
        GENERATED_NOTICE,
        f"<!-- Canonical source: {contract['canonical_source']} -->",
        f"# {title}",
        "",
        (
            f"> **Preflight status:** `{contract['status']}`; dependency "
            f"`{dependency['chunk_id']}` / `{dependency['phase_id']}` is "
            f"`{dependency['state']}`. {dependency['consequence']}"
        ),
        "",
        f"**Work item:** `{work_item}`",
        "",
    ]


def _economics_lines(data: Mapping[str, Any], economics: Mapping[str, Any]) -> list[str]:
    global_economics = _mapping(data["economics_contract"])
    range_structure = _mapping(global_economics["range_structure"])
    return [
        "## Symbolic economics",
        "",
        f"- **Model:** `{economics['model']}`",
        f"- **Range ID:** `{economics['range_id']}`",
        f"- **Anchor ID:** `{economics['anchor_id']}`",
        f"- **Approval gate:** `{economics['approval_gate']}`",
        f"- **Public price:** `{economics['public_price']}`",
        f"- **Capacity rule:** {economics['capacity_rule']}",
        f"- **Discount rule:** {economics['discount_rule']}",
        "",
        "### Public economics boundary",
        "",
        str(global_economics["public_rule"]),
        "",
        str(global_economics["private_anchor_rule"]),
        "",
        str(range_structure["public_representation"]),
        "",
    ]


def _effect_boundary_lines(data: Mapping[str, Any]) -> list[str]:
    effects = _sequence(_mapping(data["contract"])["prohibited_preflight_effects"])
    return [
        "## Preflight effect boundary",
        "",
        "The canonical contract prohibits:",
        "",
        *_bullet_lines(effects),
        "",
    ]


def render_offer_page(
    data: Mapping[str, Any],
    offer: Mapping[str, Any],
    work_item: str,
    *,
    front_door_cta: str | None = None,
) -> str:
    """Render one offer without adding scope or terms beyond the source."""
    lines = _preamble(data, str(offer["name"]), work_item)
    if front_door_cta:
        lines.extend([f"{FRONT_DOOR_MARKER} {front_door_cta}", ""])
    lines.extend(
        [
            "## Decision contract",
            "",
            f"- **Offer ID:** `{offer['id']}`",
            f"- **Stage:** `{offer['stage']}`",
            f"- **Position:** `{offer['position']}`",
            f"- **Buyer:** {offer['buyer']}",
            f"- **Trigger:** {offer['trigger']}",
            f"- **Promise:** {offer['promise']}",
            f"- **Timeline:** {offer['timeline']}",
            "",
            "## Entry criteria",
            "",
            *_bullet_lines(_sequence(offer["entry_criteria"])),
            "",
            "## Outputs",
            "",
            *_bullet_lines(_sequence(offer["deliverables"])),
            "",
            "## Bounded authority",
            "",
            f"**Mode:** `{_mapping(offer['authority'])['mode']}`",
            "",
            str(_mapping(offer["authority"])["boundary"]),
            "",
            "## Exclusions",
            "",
            *_bullet_lines(_sequence(offer["exclusions"])),
            "",
            "## Acceptance",
            "",
            str(_mapping(offer["evidence"])["acceptance"]),
            "",
            "### Acceptance evidence artifacts",
            "",
            *_bullet_lines(_sequence(_mapping(offer["evidence"])["artifacts"])),
            "",
            "## Handoff",
            "",
            str(offer["handoff"]),
            "",
            "## Escalation",
            "",
            *_bullet_lines(_sequence(offer["escalation"])),
            "",
            "## Claim boundaries",
            "",
            _code_values(_sequence(offer["claim_refs"])),
            "",
        ]
    )
    lines.extend(_economics_lines(data, _mapping(offer["economics"])))
    lines.extend(_effect_boundary_lines(data))
    return "\n".join(lines).rstrip() + "\n"


def render_partnership_page(
    data: Mapping[str, Any],
    offer: Mapping[str, Any],
    partner_audience: Mapping[str, Any],
) -> str:
    """Render the L3 partnership diligence boundary without a public CTA."""
    lines = _preamble(data, str(offer["name"]), WORK_ITEMS["partnership_review"])
    lines.extend(
        [
            "## Access and visibility",
            "",
            f"- **Disclosure entry:** `{offer['disclosure_entry']}`",
            f"- **Position:** `{offer['position']}`",
            f"- **Public call to action:** `{str(offer['public_cta']).lower()}`",
            f"- **Public door:** `{str(partner_audience['public_door']).lower()}`",
            "",
            str(partner_audience["primary_cta"]),
            "",
        ]
    )
    body = render_offer_page(
        data,
        offer,
        WORK_ITEMS["partnership_review"],
    ).splitlines()
    decision_start = body.index("## Decision contract")
    lines.extend(body[decision_start:])
    return "\n".join(lines).rstrip() + "\n"


def render_qualification_page(data: Mapping[str, Any]) -> str:
    qualification = _mapping(data["qualification"])
    offer_by_id = _offer_map(data)
    audiences = _audience_map(data)
    direct_cta = str(audiences["direct_client"]["primary_cta"])
    partner_entry = str(audiences["product_operating_partner"]["primary_cta"])
    lines = _preamble(data, "Qualification and routing", "PSP-P04-W04")
    lines.extend(
        [
            f"{FRONT_DOOR_MARKER} {direct_cta}",
            "",
            f"**Partnership visibility boundary:** {partner_entry}",
            "",
            "## Offer separation",
            "",
            "| Route | Stage | Authority | Trigger |",
            "| --- | --- | --- | --- |",
        ]
    )
    for offer_id in (*PRIMARY_SEQUENCE, "partnership_review"):
        offer = offer_by_id[offer_id]
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{offer_id}`",
                    f"`{offer['stage']}`",
                    f"`{_mapping(offer['authority'])['mode']}`",
                    _table_cell(offer["trigger"]),
                )
            )
            + " |"
        )
    lines.extend(["", "## Routing priority", ""])
    for index, route in enumerate(_sequence(qualification["routing_priority"]), 1):
        lines.append(f"{index}. `{route}`")
    lines.extend(
        [
            "",
            "Rules are evaluated in this priority order; the first match is the route.",
            "",
            "## Routing rules",
            "",
            "| Priority | Rule | Route | Any | All | None |",
            "| ---: | --- | --- | --- | --- | --- |",
        ]
    )
    rules = [_mapping(rule) for rule in _sequence(qualification["rules"])]
    for rule in rules:
        lines.append(
            "| "
            + " | ".join(
                (
                    str(rule["priority"]),
                    f"`{rule['id']}`",
                    f"`{rule['route']}`",
                    _code_values(_sequence(rule["any"])),
                    _code_values(_sequence(rule["all"])),
                    _code_values(_sequence(rule["none"])),
                )
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Scenario matrix",
            "",
            "| Scenario | Facts | Expected route |",
            "| --- | --- | --- |",
        ]
    )
    for raw_scenario in _sequence(qualification["scenarios"]):
        scenario = _mapping(raw_scenario)
        facts = _mapping(scenario["facts"])
        rendered_facts = ", ".join(f"`{key}={str(value).lower()}`" for key, value in facts.items())
        lines.append(f"| `{scenario['id']}` | {rendered_facts} | `{scenario['expected_route']}` |")
    lines.extend(
        [
            "",
            "## Decline boundary",
            "",
            str(qualification["decline_language"]),
            "",
            "## Human-review boundary",
            "",
            str(qualification["review_language"]),
            "",
        ]
    )
    global_economics = _mapping(data["economics_contract"])
    range_structure = _mapping(global_economics["range_structure"])
    lines.extend(
        [
            "## Public economics boundary",
            "",
            str(global_economics["public_rule"]),
            "",
            str(global_economics["private_anchor_rule"]),
            "",
            str(range_structure["public_representation"]),
            "",
        ]
    )
    lines.extend(_effect_boundary_lines(data))
    return "\n".join(lines).rstrip() + "\n"


def render_artifacts(data: Mapping[str, Any]) -> dict[str, str]:
    """Return the complete deterministic artifact manifest."""
    offer_by_id = _offer_map(data)
    audiences = _audience_map(data)
    direct_cta = str(audiences["direct_client"]["primary_cta"])
    artifacts = {
        OFFER_FILES["audit"]: render_offer_page(
            data,
            offer_by_id["audit"],
            WORK_ITEMS["audit"],
            front_door_cta=direct_cta,
        ),
        OFFER_FILES["install"]: render_offer_page(data, offer_by_id["install"], WORK_ITEMS["install"]),
        OFFER_FILES["retainer"]: render_offer_page(data, offer_by_id["retainer"], WORK_ITEMS["retainer"]),
        QUALIFICATION_FILE: render_qualification_page(data),
        OFFER_FILES["partnership_review"]: render_partnership_page(
            data,
            offer_by_id["partnership_review"],
            audiences["product_operating_partner"],
        ),
    }
    return dict(sorted(artifacts.items()))


def _offer_coverage_values(data: Mapping[str, Any], offer: Mapping[str, Any]) -> list[tuple[str, str]]:
    values: list[tuple[str, str]] = []
    for field in (
        "id",
        "name",
        "stage",
        "position",
        "buyer",
        "trigger",
        "promise",
        "timeline",
        "handoff",
    ):
        values.append((field, str(offer[field])))
    for field in ("entry_criteria", "deliverables", "exclusions", "escalation", "claim_refs"):
        values.extend((field, str(item)) for item in _sequence(offer[field]))
    authority = _mapping(offer["authority"])
    values.extend((f"authority.{field}", str(authority[field])) for field in REQUIRED_AUTHORITY_FIELDS)
    evidence = _mapping(offer["evidence"])
    values.append(("evidence.acceptance", str(evidence["acceptance"])))
    values.extend(("evidence.artifacts", str(item)) for item in _sequence(evidence["artifacts"]))
    economics = _mapping(offer["economics"])
    values.extend((f"economics.{field}", str(economics[field])) for field in REQUIRED_ECONOMICS_FIELDS)
    if "disclosure_entry" in offer:
        values.append(("disclosure_entry", str(offer["disclosure_entry"])))
    if "public_cta" in offer:
        values.append(("public_cta", str(offer["public_cta"]).lower()))
    global_economics = _mapping(data["economics_contract"])
    values.extend(
        (
            ("economics_contract.public_rule", str(global_economics["public_rule"])),
            (
                "economics_contract.private_anchor_rule",
                str(global_economics["private_anchor_rule"]),
            ),
            (
                "economics_contract.range_structure.public_representation",
                str(_mapping(global_economics["range_structure"])["public_representation"]),
            ),
        )
    )
    return values


def validate_offer_page_coverage(
    data: Mapping[str, Any],
    offer: Mapping[str, Any],
    text: str,
    label: str,
) -> list[str]:
    errors: list[str] = []
    for field, value in _offer_coverage_values(data, offer):
        if value not in text:
            errors.append(f"{label} missing canonical {field} value: {value}")
    return errors


def validate_qualification_page_coverage(data: Mapping[str, Any], text: str, label: str) -> list[str]:
    errors: list[str] = []
    qualification = _mapping(data["qualification"])
    required_values: list[tuple[str, str]] = [
        ("decline_language", str(qualification["decline_language"])),
        ("review_language", str(qualification["review_language"])),
    ]
    audiences = _audience_map(data)
    required_values.extend(
        (
            (
                "direct_client.primary_cta",
                str(audiences["direct_client"]["primary_cta"]),
            ),
            (
                "product_operating_partner.primary_cta",
                str(audiences["product_operating_partner"]["primary_cta"]),
            ),
        )
    )
    for offer_id in (*PRIMARY_SEQUENCE, "partnership_review"):
        offer = _offer_map(data)[offer_id]
        required_values.extend(
            (
                ("offer.id", offer_id),
                ("offer.stage", str(offer["stage"])),
                ("offer.authority.mode", str(_mapping(offer["authority"])["mode"])),
                ("offer.trigger", str(offer["trigger"])),
            )
        )
    required_values.extend(("routing_priority", str(route)) for route in _sequence(qualification["routing_priority"]))
    for raw_rule in _sequence(qualification["rules"]):
        rule = _mapping(raw_rule)
        for field in ("id", "route", "priority"):
            required_values.append((f"rule.{field}", str(rule[field])))
        for field in ("any", "all", "none"):
            required_values.extend((f"rule.{field}", str(item)) for item in _sequence(rule[field]))
    for raw_scenario in _sequence(qualification["scenarios"]):
        scenario = _mapping(raw_scenario)
        required_values.extend(
            (
                ("scenario.id", str(scenario["id"])),
                ("scenario.expected_route", str(scenario["expected_route"])),
            )
        )
        required_values.extend(
            ("scenario.fact", f"{key}={str(value).lower()}") for key, value in _mapping(scenario["facts"]).items()
        )
    economics = _mapping(data["economics_contract"])
    required_values.extend(
        (
            ("economics_contract.public_rule", str(economics["public_rule"])),
            (
                "economics_contract.private_anchor_rule",
                str(economics["private_anchor_rule"]),
            ),
            (
                "economics_contract.range_structure.public_representation",
                str(_mapping(economics["range_structure"])["public_representation"]),
            ),
        )
    )
    for field, value in required_values:
        if value not in text:
            errors.append(f"{label} missing canonical {field} value: {value}")
    return errors


def validate_front_door_ctas(artifacts: Mapping[str, str]) -> list[str]:
    """Ensure front-door language routes only to the Audit."""
    errors: list[str] = []
    found: list[tuple[str, str]] = []
    for filename, text in artifacts.items():
        for line in text.splitlines():
            if line.startswith(FRONT_DOOR_MARKER):
                found.append((filename, line))
                lowered = line.lower()
                if "agentic delivery audit" not in lowered:
                    errors.append(f"front-door CTA in {filename} does not route to the Audit")
                if "partner" in lowered or "operator" in lowered:
                    errors.append(f"public partnership promotion leaked into front-door CTA in {filename}")
    partner_file = OFFER_FILES["partnership_review"]
    if any(filename == partner_file for filename, _line in found):
        errors.append("partnership artifact must not contain a front-door CTA")
    expected_locations = {OFFER_FILES["audit"], QUALIFICATION_FILE}
    actual_locations = {filename for filename, _line in found}
    if actual_locations != expected_locations:
        errors.append(
            f"front-door CTA locations drifted: expected {sorted(expected_locations)}, found {sorted(actual_locations)}"
        )
    return errors


def validate_artifact_directory(data: Mapping[str, Any], output_dir: Path = OUTPUT_DIR) -> list[str]:
    """Compare materialized files with the source-derived manifest."""
    errors: list[str] = []
    expected = render_artifacts(data)
    actual: dict[str, str] = {}
    if not output_dir.exists():
        return [f"missing offer artifact directory: {output_dir}"]
    actual_files = {path.relative_to(output_dir).as_posix() for path in output_dir.rglob("*.md") if path.is_file()}
    for missing in sorted(EXPECTED_FILES - actual_files):
        errors.append(f"missing generated offer artifact: {missing}")
    for unexpected in sorted(actual_files - EXPECTED_FILES):
        errors.append(f"unexpected unmanaged offer artifact: {unexpected}")
    for filename in sorted(actual_files):
        path = output_dir / filename
        text = path.read_text(encoding="utf-8")
        actual[filename] = text
        errors.extend(validate_artifact_text(filename, text))
        if filename in expected and text != expected[filename]:
            errors.append(f"generated offer artifact drifted from canonical YAML: {filename}")

    offer_by_id = _offer_map(data)
    for offer_id, filename in OFFER_FILES.items():
        if filename in actual:
            errors.extend(
                validate_offer_page_coverage(
                    data,
                    offer_by_id[offer_id],
                    actual[filename],
                    filename,
                )
            )
    if QUALIFICATION_FILE in actual:
        errors.extend(
            validate_qualification_page_coverage(
                data,
                actual[QUALIFICATION_FILE],
                QUALIFICATION_FILE,
            )
        )
    errors.extend(validate_front_door_ctas(actual))
    return errors


def validate_repository(data: Mapping[str, Any], output_dir: Path = OUTPUT_DIR) -> list[str]:
    errors = validate_contract(data)
    if errors:
        return errors
    return validate_artifact_directory(data, output_dir)


def write_artifacts(data: Mapping[str, Any], output_dir: Path = OUTPUT_DIR) -> tuple[Path, ...]:
    errors = validate_contract(data)
    if errors:
        raise OfferArtifactValidationError("\n".join(errors))
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, text in render_artifacts(data).items():
        path = output_dir / filename
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return tuple(written)


def load_contract(path: Path = CONTRACT_PATH) -> dict[str, Any]:
    loaded = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(loaded, dict):
        raise OfferArtifactValidationError("contract root must be a mapping")
    return loaded


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render", action="store_true", help="regenerate the five offer artifacts")
    parser.add_argument("--check", action="store_true", help="validate source and generated artifacts")
    args = parser.parse_args()
    if not args.render and not args.check:
        parser.error("choose --render and/or --check")

    try:
        data = load_contract()
    except (OSError, yaml.YAMLError, OfferArtifactValidationError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    source_errors = validate_contract(data)
    if source_errors:
        for error in source_errors:
            print(f"FAIL: {error}", file=sys.stderr)
        return 1

    if args.render:
        written = write_artifacts(data)
        print(f"rendered {len(written)} PSP-P04 offer artifacts in {OUTPUT_DIR.relative_to(ROOT)}")
    if args.check:
        errors = validate_artifact_directory(data)
        if errors:
            for error in errors:
                print(f"FAIL: {error}", file=sys.stderr)
            return 1
        print("PASS: 5 PSP-P04 offer artifacts match the canonical contract and public-safety boundaries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
